### ISSUE TITLE
XSRF check failed error

### ISSUE THREAD

**Issue by ThatGuySam** [fyyyyy/Toggl-to-Jira-Chrome-Extension#10]
First off, thanks for building this for free so I don't have to pay $10/month to some random software company on the internet. 

I'm getting the following error

<img width="595" alt="screenshot 2019-01-18 10 02 47" src="https://user-images.githubusercontent.com/2830379/51399188-fb39c180-1b0a-11e9-841b-82ecf3ae6e1b.png">

MacOS Mojave 10.14.2
Chrome 71.0.3578.98
Toggle Chrome Plugin 1.19.1

I'm not really sure what else context you may need.

**Comment by fyyyyy** [comment]
Can you install the latest version of the plugin ?

**Comment by ThatGuySam** [comment]
Looks like you got it to work!!

<img width="333" alt="screenshot 2019-01-20 13 35 50" src="https://user-images.githubusercontent.com/2830379/51444116-edc23a00-1cb8-11e9-8a9b-d613936d2f28.png">

**Comment by ThatGuySam** [comment]
I did notice another small bug. 

I get this error whenever I try to record a time less than 1 minute

<img width="554" alt="screenshot 2019-01-20 13 31 15" src="https://user-images.githubusercontent.com/2830379/51444128-15b19d80-1cb9-11e9-9f6b-43a630a2f93c.png">

**Comment by fyyyyy** [comment]
It was fixed long time ago :)
You had a very old version like 1 year old. Where did you find this ?

**Comment by maartendeblock** [comment]
I also have the "XSRF check failed error" message. Installed version of the plugin is 2.1.2 found at https://chrome.google.com/webstore/detail/toggl-to-jira/anbbcnldaagfjlhbfddpjlndmjcgkdpf/

How can I solve it?

Tnx

**Comment by maartendeblock** [comment]
> I also have the "XSRF check failed error" message. Installed version of the plugin is 2.1.2 found at https://chrome.google.com/webstore/detail/toggl-to-jira/anbbcnldaagfjlhbfddpjlndmjcgkdpf/
> 
> How can I solve it?
> 
> Tnx

Restarting the browser fully solved the problem.

**Comment by dguntin** [comment]
I have the same problem with XSRF check failed error
Im using 
![image](https://user-images.githubusercontent.com/56675814/66995087-b4471f80-f0ce-11e9-8c7c-3d05e1f0b465.png)

tnx

**Comment by fyyyyy** [comment]
make sure you are logged in to toggl and jira. Then reload the jira and toggl pages so they update their tokens.
If not, restart the browser

**Comment by so2liu** [comment]
> make sure you are logged in to toggl and jira. Then reload the jira and toggl pages so they update their tokens.
> If not, restart the browser

Hi fyyyyy,

sorry to interrupt you. I am a web developer and now working on a tool about jira for my company. I am facing the same problem 403 XSRF check failed. When I send POST request in browser (localhost), I get 403. However, when I use Postman, it will succeed. 

I've tried User-Agent, "X-Atlassian-Token": "nocheck" / "no-check", but neither works. I am using basic auth.

I searched and it looks like you've solved it. Could you tell me how did you do it?

Thank you very much!

Yang Liu

**Comment by jhelmink** [comment]
> When I send POST request in browser (localhost)

If you are logged in to both Jira and Toggl the plugin will work, if you are trying to manually make the Jira API calls you might be bypassing the request interception that happens in the background when the plugin is loaded; 
https://github.com/fyyyyy/Toggl-to-Jira-Chrome-Extension/blob/master/background.js
