### ISSUE TITLE
Timezone mismatch?

### ISSUE THREAD

**Issue by maartendeblock** [fyyyyy/Toggl-to-Jira-Chrome-Extension#12]
All worklogs are one hour of (one hour too early). Could this be a timezone mismatch?

**Comment by fyyyyy** [comment]
In toggle, in the plugin view or in Jira worklog ?

**Comment by maartendeblock** [comment]
I debugged it and the entry.start (first used on line 177 of parser.js) is shifted. This causes it to be saved incorrectly in Jira.

**Comment by fyyyyy** [comment]
Hmm yeah that date conversion **toJiraWhateverDateTime** looks a bit messy. I cant remember when/why i wrote that but it seems JIRA expects a very strange date format.
Probably safer to use moment.js for date conversion.

**Comment by jhelmink** [comment]
I think this might be fixed in my fork. Have created a Pull Request.
Toggl returns everything in UTC, and Jira is expecting everything in UTC, just with a different format.
