### ISSUE TITLE
Suggestion for handling worklog comments

### ISSUE THREAD

**Issue by nixpix** [fyyyyy/Toggl-to-Jira-Chrome-Extension#14]
From my understanding, currently the extension takes the first word of the Toggl time entry description and checks on JIRA if an item with that key exists. then adds the toggl time entry as a worklog.

Could an option be added so that when activated the plugin would use the rest of the Toggl description as the worklog comment for the JIRA issue?

Example:
I have a toggl entry that look like this
LOM-951 Add dropdown menu to element on site

Currently the extension takes the "LOM-951" and searches for the item on JIRA. If it finds the items it adds the tracked time with the comment that is set in the extension options.
My proposal is to enable the extension to use the rest of the description.
So in this case: "Add dropdown menu to element on site", and to use that as the comment for that issue when logging the worklog in JIRA.
This would enable me to add meaningful comments to the worklog on Jira by editing the Toggl time entries.

Unfortunately I am not familiar with javascript and extension developing to propose a technical solution for this. But maybe somebody could add this.

Thanks.

**Comment by jhelmink** [comment]
Have added this functionality in my fork with an option to "Use Toggl description as Log Work comment" which will also append any "Default Log Work comment" if set.

I have created a Pull Request.

**Comment by fyyyyy** [comment]
merged
