### ISSUE TITLE
Hardcoded Toggl URL can cause 403s

### ISSUE THREAD

**Issue by rogatty** [fyyyyy/Toggl-to-Jira-Chrome-Extension#15]
When you go to https://www.toggl.com/login and use Google sign-in, you get redirected to https://toggl.com/app, notice the lack of `www.`. In https://github.com/fyyyyy/Toggl-to-Jira-Chrome-Extension/blob/master/parser.js#L193 there is a hardcoded `https://www.toggl.com/api/v8/time_entries` URL. Because you don't have the required cookie for `www.toggl.com` domain, you get 403 from the API and the extension doesn't work as expected.

Workaround I found is to set the account password by resetting your Toggl password and use it to log in. Would be great if the extension handled this case, though. The easiest to implement (not so great UX) would be to make the Toggl host configurable.

**Comment by fyyyyy** [comment]
should be configurable now
