### ISSUE TITLE
403 error when getting Toggl time entries

### ISSUE THREAD

**Issue by tiagojufr** [fyyyyy/Toggl-to-Jira-Chrome-Extension#19]
The app has not been working for me for some weeks now. I'm getting a 403 when calling https://www.toggl.com/api/v8/time_entries?start_date=2020-01-01T00:00:00.000Z&end_date=2020-01-31T00:00:00.000Z. I had this error in the past, but logging out and logging back in at the Toggl website solved it. Now, that quick fix doesn't work anymore.
I've noticed that the Toggl website is now using the v9 API and this app still uses the v8. Can this be the issue?

**Comment by jcwoos** [comment]
Olá Tiago, você chegou a configurar o token da api na extensão? Essa opção foi adicionada recentemente após esse erro ter começado a aparecer para mim também.

**Comment by tiagojufr** [comment]
Já experimentei isso também mas mesmo assim não funciona...

**Comment by jcwoos** [comment]
Olhando no github do Toggl, eles ainda mostram a documentação da API 8, mas esso não deve ser o problema, pois acabei de remover extensão e coloca-la novamente e continua funcionando normalmente.
Você consegue ver se os requests através da extensão para a API deles está com o header 'Authorization' ?

**Comment by tiagojufr** [comment]
Não, esse header não está presente. Aqui está a lista de headers enviados (censurei alguns ids por razões de segurança):
```
:authority: www.toggl.com
:method: GET
:path: /api/v8/time_entries?start_date=2020-01-05T00:00:00.000Z&end_date=2020-01-06T00:00:00.000Z
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,pt;q=0.8
access-control-allow-origin: *
cache-control: no-cache
cookie: __stripe_sid=<censurado>; __stripe_mid=<censurado>; _jsuid=<censurado>; _first_pageview=1; intercom-id-ayixs927=<censurado>; _ga_0CMCDCRQ5M=<censurado>; intercom-session-ayixs927=<censurado>; _ga=<censurado>; _gid=<censurado>
forgeme: true
origin: https://jira.atlassian.net
pragma: no-cache
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
x-atlassian-token: nocheck
```

Eu uso um JIRA privado da minha empresa, no entanto o `origin` está com o valor do JIRA público... não sei se isso poderá ser o problema.

**Comment by jcwoos** [comment]
Esse header é necessário para que a extensão possa carregar os registros do Toggl.
Se o seu nome e email estiver aparecendo na lista das tarefas que a extensão carrega, então a extensão está conseguindo acessar a API do Jira sem problemas.

Imagino que você já tenta tentado fechar e abrir novamente o Chrome, e ativada a opção 'Permitir acesso aos URLs do arquivo' nas configurações da extensão em 'Gerenciar extensões'.. certo?

**Comment by tiagojufr** [comment]
Pensava que já tinha feito isso mas na verdade costumo hibernar sempre o PC por isso já não reiniciava o Chrome há alguns dias. Agora que o reiniciei já funcionou 😅.
Muito obrigado pelo suporte e parabéns pela app! Ajuda-me bastante no meu dia a dia!

**Comment by jcwoos** [comment]
Tranquilo, abraço!
