### ISSUE TITLE
Console logging errror 403 since 2020

### ISSUE THREAD

**Issue by takaite** [fyyyyy/Toggl-to-Jira-Chrome-Extension#20]
I believe that API has changed and is not accepting the authentication.

**Comment by jcwoos** [comment]
Hello takaite,
in the options, you can configure the toggl api token.
With this token, all requests to toggl will have the 'authorization' header.

**Comment by jhelmink** [comment]
Toggl API token is now required for all requests. I've updated the options to make this clearer, and also have a Test to confirm connections to Jira and Toggl are working OK.

Have created a Pull Request.

**Comment by fyyyyy** [comment]
thanks, merged
