### ISSUE TITLE
Log work to JIRA message

### ISSUE THREAD

**Issue by jhelmink** [fyyyyy/Toggl-to-Jira-Chrome-Extension#24]
There is a warning message at the bottom of the popup: "Logging repeatedly will add new time logs for the same JIRA task, instead of overwriting the old log. So log only once per Toggl entry."

Is this still valid? From the code and my usage it looks like you'd always be prevented from being able to log anything twice since it checks the Jira work entries and matches them against the toggl entries?

I think we should remove this message, but wanted to make sure I wasn't missing something first!

**Comment by fyyyyy** [comment]
I guess we could remove this

**Comment by jhelmink** [comment]
This was removed in the latest version.
