### ISSUE TITLE
blocked by CORS policy on toggl website

### ISSUE THREAD

**Issue by svob** [fyyyyy/Toggl-to-Jira-Chrome-Extension#25]
The extensions is causing the XHR requests to be blocked by CORS policy on toggl site, due to this u can't login on https://toggl.com/track/login/

**Comment by jhelmink** [comment]
The latest version of this tool does not intercept Toggl requests. It makes API calls instead. So it won't be interfering with your Toggl login process.

**Comment by jhelmink** [comment]
@fyyyyy did the latest version of the code get published to the Chrome extension store?

**Comment by fyyyyy** [comment]
Oh sorry, i uploaded v 2.2.0 to the webstore.
Is there a way for chrome webstore to update from github master branch automatically?

**Comment by jhelmink** [comment]
Looks like Github Actions might do it; https://github.com/features/actions
There are a few prebuilt actions in the market place that look promising;
https://github.com/marketplace?category=deployment&type=actions&query=chrome
Would take some time configuring and testing though.

**Comment by fyyyyy** [comment]
This looks pretty cool, we would need to add a build though which creates a /dist/plugin.zip file

**Comment by jhelmink** [comment]
Looks like there is an action for that too;
https://github.com/marketplace/actions/zip-release
So it would be a complete CI pipeline.
