### ISSUE TITLE
New Toggl API domain

### ISSUE THREAD

**Issue by tiagojufr** [fyyyyy/Toggl-to-Jira-Chrome-Extension#28]
Just got an email from Toggl saying I'm using https://www.toggl.com/api and I should now be using https://api.track.toggl.com/api as https://www.toggl.com/api will be dropped after 'June 30th 2021'.
Checked the code and reproduced the requests the extension does in Postman with the new domain and they seem to work fine. 
Can you please update the URLs?

**Comment by fyyyyy** [comment]
fixed in #29
