### ISSUE TITLE
doesn't work, idk

### ISSUE THREAD

**Issue by automaticgiant** [fyyyyy/Toggl-to-Jira-Chrome-Extension#5]
installed, added our jira server url, without trailing slash, nothing happens when i try to load entries.
tried with and without inputting a end date.
no console errors, no network requests.
what should i be looking for?

chrome: Version 62.0.3202.94 (Official Build) (64-bit)
Toggl to Jira 2.0.5

i'm so this doesn't work right now :(

**Comment by fyyyyy** [comment]
I'm sorry but the webstore version is out of date, i will try to update it over lunch. Try cloning this folder and adding it to chrome extensions.

**Comment by fyyyyy** [comment]
v 2.1. is released in chrome webstore, it should fix it.
Let me know :)
